import type { Metadata } from 'next';
import Header from '@/components/Header/Header';
import { Mina, Nunito_Sans, Sora } from 'next/font/google';
import Footer from '@/components/Footer/Footer';
import './globals.css';

const nunito = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700'],
});
const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${sora.variable}`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
